
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SIA' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for View Animation
#https://cocoapods.org/pods/Canvas
#https://github.com/CanvasPod/Canvas

pod 'Canvas', '~> 0.1'

# Pods for keyboard textfield
#https://cocoapods.org/pods/IQKeyboardManagerSwift
#https://github.com/hackiftekhar/IQKeyboardManager

pod 'IQKeyboardManagerSwift', '~> 6.0'

# Pods for animation of text field, buttons and many more
#https://cocoapods.org/pods/Material
#https://github.com/CosmicMind/Material

pod 'Material', '~> 2.0'

end




